name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches:
      - dev
      - main
    paths:
      - "**.js"
      - "**.sol"
  pull_request:
    branches:
      - dev
      - main
    paths:
      - "**.js"
      - "**.sol"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          yarn install --no-lockfile
          yarn run prettier:solidity
          yarn test
